---
-  name: "install and run prometheus"
   shell: |
      wget https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
      tar xvfz prometheus-2.19.0.linux-amd64.tar.gz
      cd  prometheus-2.19.0.linux-amd64/
      ./prometheus --config.file=./prometheus.yml
     
